---
- name: copy public key
  hosts: all
  tasks:
    - name: using authorized module
      ansible.posix.authorized_key:
        user: guru
        state: present
        key: "{{ lookup('file', '/home/guru/.ssh/id_rsa.pub') }}"